### ISSUE TITLE
testing in ubuntu 14.10 (Languages do not work)

### ISSUE THREAD

**Issue by dzyasseron** [Alfanous-team/alfanous#432] opened 2015-02-22 21:17 UTC
عند تغيير اللغة من الانجليزية الى الفرنسية يطلب اعادة تشغيل البرنامج
وبعد اعادة تشغيله يظهر بالانجليزية بدون أي تغير
بالإضافة إلى أن الحروف العربية والفرنسية لاتظهر بالشكل الصحيح
v0.7.04 on ubuntu 14.10
![huuu](https://cloud.githubusercontent.com/assets/5055803/6320517/47fb6a62-bae0-11e4-875d-d3c6e66d1942.png)

**Comment by zsmahi** [comment] 2015-02-23 09:11
The Same Here, 
Language is always English

**Comment by assem-ch** [comment] 2015-02-27 00:00
@zsmahi @dzyasseron could you test it again cause I made a fix : 

     sudo apt-get update
     sudo apt-get upgrade alfanous

**Comment by dzyasseron** [comment] 2015-02-27 09:44
alfanous not work
تعطل البرنامج، لايوجد في القائمة
alfanous-desktop: command not found
alfanousDesktop: command not found

**Comment by assem-ch** [comment] 2015-02-27 12:55
@dzyasseron could you test it again

**Comment by Zinebl** [comment] 2015-02-27 13:15
@assem-ch it works correctly now i have "alfanous" , but the language didn't change, always English
![screenshot from 2015-02-27 14 11 00](https://cloud.githubusercontent.com/assets/5882388/6412980/c794f4f2-be8a-11e4-94a9-14b2625b09cb.png)

**Comment by Zinebl** [comment] 2015-02-27 13:22
check also this 
![screenshot from 2015-02-27 14 18 54](https://cloud.githubusercontent.com/assets/5882388/6413096/04362894-be8c-11e4-900b-85bdce80164e.png)

**Comment by assem-ch** [comment] 2015-02-27 14:14
Thanks @Zinebl , the second one I just fixed it.

For the language issue, could you try:

     LANG=ar alfanous-desktop

and send me the result of 

     locate alfanousDesktop

**Comment by Zinebl** [comment] 2015-02-27 14:40
u r welcome, we don't need to try this. i choose "arabic " and it works correctly, it works also for all styles
![screenshot from 2015-02-27 15 26 28](https://cloud.githubusercontent.com/assets/5882388/6414224/17573684-be96-11e4-9d21-93d0ace53db4.png)
also see the above bar of alfanous in french(the previous screenshot, the title is in french lang, do you add the translation of alfanous in french? or it's a bug in app

**Comment by assem-ch** [comment] 2015-02-27 14:47
@Zinebl Great! . About the french, its' not a bug, its just french translation is not complete. only English and Arabic are complete.

**Comment by Zinebl** [comment] 2015-02-27 14:56
ok, i expect that when it work in "arabic" , @assem-ch  just a notice  if u can change the color of selected elemt it's better cause it's not  readable using white

**Comment by assem-ch** [comment] 2015-02-27 15:00
What elements? menu?

**Comment by Zinebl** [comment] 2015-02-27 15:01
yes

**Comment by assem-ch** [comment] 2015-02-27 15:11
@Zinebl fixed, thanks. Any new remarks , feel free to tell me about them

**Comment by assem-ch** [comment] 2015-02-27 15:12
@dzyasseron , @zsmahi did the languages works for you too so I can close the issue

**Comment by Zinebl** [comment] 2015-02-27 15:16
Ok @assem-ch;

**Comment by zsmahi** [comment] 2015-02-27 15:25
Arabic works perfectly here @assem-ch

**Comment by assem-ch** [comment] 2015-02-27 15:32
Thanks @zsmahi

**Comment by dzyasseron** [comment] 2015-02-27 18:09
كنت أجرب وأجرب
حذفت البرنامج وأعدت تثبيته بدون فائدة
لا يعمل أبدا ولا يظهر في القائمة
لدي:
ubuntu 14.10 XFCE4.4

**Comment by assem-ch** [comment] 2015-02-27 18:12
@dzyasseron  strange , try this:
      
```
   sudo apt-get purge alfanous python-alfanous
   sudo apt-get update
   sudo apt-get install alfanous
   alfanous-desktop
  


```

then send me the results of ``` locate alfanous.desktop```

**Comment by dzyasseron** [comment] 2015-02-27 20:53
it's work fine
thank you

**Comment by assem-ch** [comment] 2015-02-27 21:10
@dzyasseron  thank you too

**Closed by assem-ch** 2015-02-27 21:10 UTC
Labels: bug, desktop
